const APP_DATA = {
        "metadata": {
          "vendors": [
            "2GiC",
            "ATOUTEK",
            "ATELIERS DU BOCAGE",
            "AVEGOTT",
            "BRING IT BACK",
            "COQWEL",
            "DRJL",
            "E-RECYCLE",
            "ECO MOBILE SOLUTION",
            "ECOD'AIR - EA"
          ],
          "marques": [
            "Apple",
            "Samsung",
            "Xiaomi",
            "Sony",
            "Huawei",
            "Microsoft",
            "Motorola",
            "Nokia",
            "Honor",
            "Echo"
          ],
          "grades": [
            "FAIR",
            "GOOD",
            "MINT",
            "VERY_GOOD"
          ],
          "couleurs": [
            "Argent",
            "Blanc",
            "Bleu",
            "Gris Sidéral",
            "Noir",
            "Or",
            "Rose"
          ],
          "capacites": [16, 32, 64, 128, 256, 512],
          "stats": {
            "totalProduits": 20,
            "produitsEnStock": 12,
            "produitsSansStock": 8,
            "prixMoyen": 349.50
          }
        },
        "products": [
            {
                sku: "W-18472-16-17",
                Marque: "Apple",
                Modele: "iPhone 13 Pro",
                Couleur: "Gris Sidéral",
                Capacite: 256,
                Grade: "MINT",
                Quantite: 5,
                Prix: 899,
                Status: "validated",
                "Nom vendeur": "2GiC"
            },
            {
                sku: "W-18473-32-17",
                Marque: "Samsung",
                Modele: "Galaxy S23 Ultra",
                Couleur: "Noir",
                Capacite: 512,
                Grade: "VERY_GOOD",
                Quantite: 3,
                Prix: 1099,
                Status: "validated",
                "Nom vendeur": "ATOUTEK"
            },
            {
                sku: "W-18474-64-17",
                Marque: "Xiaomi",
                Modele: "13 Pro",
                Couleur: "Bleu",
                Capacite: 256,
                Grade: "GOOD",
                Quantite: 0,
                Prix: 599,
                Status: "validated",
                "Nom vendeur": "ATELIERS DU BOCAGE"
            },
            {
                sku: "W-18475-128-17",
                Marque: "Apple",
                Modele: "iPhone 12",
                Couleur: "Or",
                Capacite: 128,
                Grade: "MINT",
                Quantite: 7,
                Prix: 699,
                Status: "validated",
                "Nom vendeur": "AVEGOTT"
            },
            {
                sku: "W-18476-256-17",
                Marque: "Google",
                Modele: "Pixel 7 Pro",
                Couleur: "Argent",
                Capacite: 256,
                Grade: "VERY_GOOD",
                Quantite: 2,
                Prix: 799,
                Status: "validated",
                "Nom vendeur": "BRING IT BACK"
            },
            {
                sku: "W-18477-128-17",
                Marque: "OnePlus",
                Modele: "9 Pro",
                Couleur: "Vert",
                Capacite: 256,
                Grade: "GOOD",
                Quantite: 0,
                Prix: 549,
                Status: "validated",
                "Nom vendeur": "COQWEL"
            },
            {
                sku: "W-18478-512-17",
                Marque: "Apple",
                Modele: "iPhone 14",
                Couleur: "Rose",
                Capacite: 512,
                Grade: "MINT",
                Quantite: 4,
                Prix: 999,
                Status: "validated",
                "Nom vendeur": "DRJL"
            },
            {
                sku: "W-18479-256-17",
                Marque: "Samsung",
                Modele: "Galaxy Z Fold 4",
                Couleur: "Bronze",
                Capacite: 512,
                Grade: "MINT",
                Quantite: 1,
                Prix: 1499,
                Status: "validated",
                "Nom vendeur": "E-RECYCLE"
            },
            {
                sku: "W-18480-128-17",
                Marque: "Huawei",
                Modele: "P40 Pro",
                Couleur: "Noir",
                Capacite: 256,
                Grade: "GOOD",
                Quantite: 0,
                Prix: 499,
                Status: "validated",
                "Nom vendeur": "ECO MOBILE SOLUTION"
            },
            {
                sku: "W-18481-64-17",
                Marque: "Sony",
                Modele: "Xperia 1 IV",
                Couleur: "Violet",
                Capacite: 256,
                Grade: "VERY_GOOD",
                Quantite: 3,
                Prix: 899,
                Status: "validated",
                "Nom vendeur": "ECOD'AIR - EA"
            },
            {
                sku: "W-18482-256-17",
                Marque: "Apple",
                Modele: "iPhone 13 Mini",
                Couleur: "Bleu",
                Capacite: 128,
                Grade: "FAIR",
                Quantite: 0,
                Prix: 599,
                Status: "validated",
                "Nom vendeur": "EXCEPCIO LOGISTIQUE"
            },
            {
                sku: "W-18483-128-17",
                Marque: "Oppo",
                Modele: "Find X5 Pro",
                Couleur: "Blanc",
                Capacite: 256,
                Grade: "MINT",
                Quantite: 2,
                Prix: 799,
                Status: "validated",
                "Nom vendeur": "FIRPO & CO"
            },
            {
                sku: "W-18484-512-17",
                Marque: "Samsung",
                Modele: "Galaxy S22+",
                Couleur: "Gris",
                Capacite: 256,
                Grade: "VERY_GOOD",
                Quantite: 4,
                Prix: 849,
                Status: "validated",
                "Nom vendeur": "GLASSY TECH"
            },
            {
                sku: "W-18485-256-17",
                Marque: "Honor",
                Modele: "Magic4 Pro",
                Couleur: "Argent",
                Capacite: 256,
                Grade: "GOOD",
                Quantite: 0,
                Prix: 699,
                Status: "validated",
                "Nom vendeur": "GZ SUPPLY"
            },
            {
                sku: "W-18486-128-17",
                Marque: "Apple",
                Modele: "iPhone 14 Pro Max",
                Couleur: "Or",
                Capacite: 512,
                Grade: "MINT",
                Quantite: 3,
                Prix: 1299,
                Status: "validated",
                "Nom vendeur": "KABILOO SARL"
            },
            {
                sku: "A-63920-11-84",
                Marque: "Apple",
                Modele: "iPhone 12 Pro Max",
                Couleur: "Bleu Pacifique",
                Capacite: 256,
                Grade: "VERY_GOOD",
                Quantite: 1,
                Prix: 849,
                Status: "validated",
                "Nom vendeur": "ATOUTEK"
                },
                {
                sku: "S-47351-08-29",
                Marque: "Samsung",
                Modele: "Galaxy Z Fold 3",
                Couleur: "Noir Fantôme",
                Capacite: 512,
                Grade: "EXCELLENT",
                Quantite: 2,
                Prix: 1299,
                Status: "validated",
                "Nom vendeur": "LARGO"
                },
                {
                sku: "X-19573-42-06",
                Marque: "Xiaomi",
                Modele: "Mi 11 Ultra",
                Couleur: "Blanc Céramique",
                Capacite: 256,
                Grade: "GOOD",
                Quantite: 5,
                Prix: 799,
                Status: "validated",
                "Nom vendeur": "EXCEPCIO LOGISTIQUE"
                },
                {
                sku: "O-85219-34-57",
                Marque: "OnePlus",
                Modele: "9 Pro",
                Couleur: "Vert Pin",
                Capacite: 128,
                Grade: "VERY_GOOD",
                Quantite: 3,
                Prix: 699,
                Status: "validated",
                "Nom vendeur": "COQWEL"
                },
                {
                sku: "H-61407-25-93",
                Marque: "Huawei",
                Modele: "P50 Pro",
                Couleur: "Or Cocoa",
                Capacite: 512,
                Grade: "EXCELLENT",
                Quantite: 1,
                Prix: 1099,
                Status: "validated",
                "Nom vendeur": "BRING IT BACK"
                },
                {
                sku: "G-37245-09-81",
                Marque: "Google",
                Modele: "Pixel 6 Pro",
                Couleur: "Sorta Sunny",
                Capacite: 256,
                Grade: "GOOD",
                Quantite: 4,
                Prix: 899,
                Status: "validated",
                "Nom vendeur": "LEASETIC"
                },
                {
                sku: "A-59103-76-18",
                Marque: "Apple",
                Modele: "iPhone 13",
                Couleur: "Lumière stellaire",
                Capacite: 128,
                Grade: "VERY_GOOD",
                Quantite: 2,
                Prix: 749,
                Status: "validated",
                "Nom vendeur": "SMART-REPA"
                },
                {
                sku: "S-82467-30-52",
                Marque: "Samsung",
                Modele: "Galaxy S21 Ultra",
                Couleur: "Argent",
                Capacite: 256,
                Grade: "EXCELLENT",
                Quantite: 1,
                Prix: 999,
                Status: "validated",
                "Nom vendeur": "AVEGOTT"
                },
                {
                sku: "N-12890-54-36",
                Marque: "Nothing",
                Modele: "Phone 1",
                Couleur: "Blanc",
                Capacite: 128,
                Grade: "GOOD",
                Quantite: 6,
                Prix: 499,
                Status: "validated",
                "Nom vendeur": "RECONNECT"
                },
                {
                sku: "M-79014-43-27",
                Marque: "Motorola",
                Modele: "Edge 30 Pro",
                Couleur: "Cosmos Blue",
                Capacite: 256,
                Grade: "VERY_GOOD",
                Quantite: 2,
                Prix: 699,
                Status: "validated",
                "Nom vendeur": "YESAGAIN"
                },
                {
                sku: "A-16539-72-04",
                Marque: "Apple",
                Modele: "iPhone 12",
                Couleur: "Violet",
                Capacite: 64,
                Grade: "EXCELLENT",
                Quantite: 3,
                Prix: 649,
                Status: "validated",
                "Nom vendeur": "E-RECYCLE"
                },
                {
                sku: "X-91283-05-60",
                Marque: "Xiaomi",
                Modele: "Redmi Note 11 Pro",
                Couleur: "Gris Graphite",
                Capacite: 128,
                Grade: "GOOD",
                Quantite: 5,
                Prix: 299,
                Status: "validated",
                "Nom vendeur": "REMADE TECHNOLOGY COMPANY"
                },
                {
                sku: "S-38157-20-94",
                Marque: "Samsung",
                Modele: "Galaxy A53 5G",
                Couleur: "Bleu Ciel",
                Capacite: 256,
                Grade: "VERY_GOOD",
                Quantite: 2,
                Prix: 449,
                Status: "validated",
                "Nom vendeur": "LE GSM"
                },
                {
                sku: "O-64028-51-73",
                Marque: "Oppo",
                Modele: "Find X5 Pro",
                Couleur: "Glaze Black",
                Capacite: 256,
                Grade: "EXCELLENT",
                Quantite: 1,
                Prix: 1199,
                Status: "validated",
                "Nom vendeur": "FIRPO & CO"
                },
                {
                sku: "H-42561-88-35",
                Marque: "Honor",
                Modele: "Magic 4 Pro",
                Couleur: "Or",
                Capacite: 512,
                Grade: "VERY_GOOD",
                Quantite: 2,
                Prix: 999,
                Status: "validated",
                "Nom vendeur": "GZ SUPPLY"
                },
                {
                sku: "S-75819-22-46",
                Marque: "Sony",
                Modele: "Xperia 1 IV",
                Couleur: "Violet",
                Capacite: 256,
                Grade: "EXCELLENT",
                Quantite: 1,
                Prix: 1399,
                Status: "validated",
                "Nom vendeur": "DRJL"
                },
                {
                sku: "R-09385-67-12",
                Marque: "Realme",
                Modele: "GT 2 Pro",
                Couleur: "Paper Green",
                Capacite: 256,
                Grade: "GOOD",
                Quantite: 4,
                Prix: 749,
                Status: "validated",
                "Nom vendeur": "TELEPHONE CENTER"
                },
                {
                sku: "V-50176-39-82",
                Marque: "Vivo",
                Modele: "X80 Pro",
                Couleur: "Cosmic Black",
                Capacite: 512,
                Grade: "VERY_GOOD",
                Quantite: 2,
                Prix: 1099,
                Status: "validated",
                "Nom vendeur": "Tech-Green"
                },
                {
                sku: "Z-13498-71-05",
                Marque: "ZTE",
                Modele: "Axon 40 Ultra",
                Couleur: "Nuit Noire",
                Capacite: 256,
                Grade: "EXCELLENT",
                Quantite: 1,
                Prix: 799,
                Status: "validated",
                "Nom vendeur": "SOFIGROUP"
                },
                {
                sku: "A-87230-53-96",
                Marque: "Asus",
                Modele: "ROG Phone 6 Pro",
                Couleur: "Blanc Storm",
                Capacite: 512,
                Grade: "VERY_GOOD",
                Quantite: 2,
                Prix: 1299,
                Status: "validated",
                "Nom vendeur": "LM ECO PRODUCTION"
                },
                {
                    sku: "A-94521-63-15",
                    Marque: "Apple",
                    Modele: "iPhone 14 Pro",
                    Couleur: "Noir Spatial",
                    Capacite: 512,
                    Grade: "MINT",
                    Quantite: 3,
                    Prix: 1199,
                    Status: "validated",
                    "Nom vendeur": "2GiC"
                },
                {
                    sku: "S-28674-44-91",
                    Marque: "Samsung",
                    Modele: "Galaxy S23+",
                    Couleur: "Crème",
                    Capacite: 256,
                    Grade: "VERY_GOOD",
                    Quantite: 4,
                    Prix: 899,
                    Status: "validated",
                    "Nom vendeur": "ATOUTEK"
                },
                {
                    sku: "X-65932-17-83",
                    Marque: "Xiaomi",
                    Modele: "12T Pro",
                    Couleur: "Bleu",
                    Capacite: 256,
                    Grade: "GOOD",
                    Quantite: 2,
                    Prix: 649,
                    Status: "validated",
                    "Nom vendeur": "ATELIERS DU BOCAGE"
                },
                
        ]
    }